services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./back-end
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 2002
      DB_NAME: signalement_db
      SECRET_KEY: your-very-secure-secret-key-change-this-in-production
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "2002"
      MYSQL_DATABASE: signalement_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./back-end/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ./back-end/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p2002"]
      timeout: 20s
      retries: 15
      interval: 10s
      start_period: 60s
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
